server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh            #路由的ID，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            Path=/payment/get/**       #断言，路径相匹配的进行路由

        - id: payment_routh2           #路由的ID，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**        #断言，路径相匹配的进行路由
            - After=2020-03-26T20:13:40.116+08:00[Asia/Shanghai]
#            - Cookie=username,fzq
#            - Header=X-Request-Id, \d+   #请求头要有X-Request-Id属性，并且值为整数的正则表达式

eureka:
  client:
    #表示向服务中心注册自己
    register-with-eureka: true
    #是否从Eureka抓取已经注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版

  instance:
    #使得在eureka界面不再显示主机名，而显示这里自定义的名字
    instance-id: cloud-gateway-service
    #在左下角可以显示IP地址
    prefer-ip-address: true
