server:
  port: 7001

eureka:
  server:
    #关闭自我保护机制，默认是true开启的
    enable-self-preservation: false
    #设置默认时间是2秒，默认是90秒
    eviction-interval-timer-in-ms: 2000

  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    #表示不向服务中心注册自己
    register-with-eureka: false
    #表示自己端就是注册中心，职责就是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个网址
      #集群指向其他Eureka
#      defaultZone: http://eureka7002.com:7002/eureka/
      #单机只有自己
      defaultZone: http://eureka7001.com:7001/eureka/
