server:
  port: 8000

eureka:
  client:
    #表示向服务中心注册自己
    register-with-eureka: false
    #是否从Eureka抓取已经注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个网址
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka  #单机版

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: cloud-hystrix-8000-order